#!/bin/bash
# Delete all local branches tracking a remote branch which has been merged into dev (or specified branch)
if [ $# -eq 0 ]; then
	BASE=origin/dev
else
	BASE=$@
fi
git fetch -p && git branch --merged $BASE | grep -v -e 'dev' -e 'versioning' -e 'master' -e '*' | xargs -I {} git branch -D {}
