#!/bin/bash
if [[ $# -ne 2 ]]; then
	echo "Usage: text \"contact(s)\" \"message\""
	exit 1
fi

number=`contacts -SHf '%mp' $1 2> /dev/null`

code=$?
if [[ code -ne 0 ]]; then
	echo "No contacts found."
	exit code
fi

numberOfNumbers=`echo "$number" | wc -l`
numberOfNumbers="$(echo -e "${numberOfNumbers}" | sed -e 's/^[[:space:]]*//')"

if [[ numberOfNumbers -ne 1 ]]; then
	echo "$numberOfNumbers contacts matched your query. Please try again."
	exit 1
fi

curl -H "Content-Type:application/json" -H "Authorization:key=***REMOVED***" "https://fcm.googleapis.com/fcm/send" -d "{\"to\":\"***REMOVED***\",\"priority\":\"high\",\"data\":{\"number\":\"$number\",\"message\":\"$2\"}}"
echo

